name: Build Verifier

on:

  push:

    branches: [ main ]
    paths:

        - 'apps/verifier/**'
  

jobs:

  build-verifier:

    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: './apps/verifier'


    steps:
        - name: 'Checkout Main'
          uses: actions/checkout@v4

        - name: Build the Docker image
        #   run: docker build . --file Dockerfile --tag ghcr.io/derekcoffman/verifier:$(date +%s)
          run: docker build . --file Dockerfile --tag ghcr.io/derekcoffman/verifier:latest
    
        - name: 'Login to GitHub Container Registry'
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: Build the Docker image
        #   run: docker build . --file Dockerfile --tag ghcr.io/derekcoffman/verifier:$(date +%s)
          run: docker build . --file Dockerfile --tag ghcr.io/derekcoffman/verifier:latest
 
        - name: Push the Docker image
          run: docker push ghcr.io/derekcoffman/verifier:$(date +%s)
          